default: &default
  encoding: unicode
  pool: 5
  timeout: 5000
  adapter: postgresql
  username: postgres
  password: Zxcv=-09
  host: localhost
  port: 5432

production:
  <<: *default
  database: chanintr_box_production

test: &test
  <<: *default
  database: chanintr_box_test

development:
  <<: *default
  database: chanintr_box_development